### ISSUE TITLE
Support Mistral/Llama2 models

### ISSUE THREAD

**Issue by sumanghosh1234** [LLukas22/vLLM-haystack-adapter#2]
Can we have support for Mistral 7B /Llama2 models as current implementation only supports Openai models.
As I was trying to use Mistral model via vLLM and it breaks now in vllm invocation layer.

 File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/pipelines/base.py", line 567, in run
    node_output, stream_id = self._run_node(node_id, node_input)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/pipelines/base.py", line 469, in _run_node
    return self.graph.nodes[node_id]["component"]._dispatch_run(**node_input)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/nodes/base.py", line 201, in _dispatch_run
    return self._dispatch_run_general(self.run, **kwargs)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/nodes/base.py", line 245, in _dispatch_run_general
    output, stream = run_method(**run_inputs, **run_params)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/nodes/prompt/prompt_node.py", line 310, in run
    results = self(**invocation_context, prompt_collector=prompt_collector)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/nodes/prompt/prompt_node.py", line 138, in __call__
    return self.prompt(prompt_template, *args, **kwargs)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/nodes/prompt/prompt_node.py", line 167, in prompt
    output = self.prompt_model.invoke(prompt, **kwargs_copy)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/nodes/prompt/prompt_model.py", line 111, in invoke
    output = self.model_invocation_layer.invoke(prompt=prompt, **kwargs)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/vllm_haystack/__init__.py", line 163, in invoke
    responses = self._execute_openai_request(
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/vllm_haystack/__init__.py", line 184, in _execute_openai_request
    _check_openai_finish_reason(result=res, payload=payload)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/utils/openai_utils.py", line 243, in _check_openai_finish_reason
    number_of_truncated_completions = sum(1 for ans in result["text"] if ans["finish_reason"] == "length")
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/utils/openai_utils.py", line 243, in <genexpr>
    number_of_truncated_completions = sum(1 for ans in result["text"] if ans["finish_reason"] == "length")
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

I tried to tweak the class but it still fails.

**Comment by LLukas22** [comment]
Uhm i think you have to be more explicite, theoretically mistral and llama2 should be supported out of the box. (I mainly build this to use llama2 based models).

There are 2 Options here: 

- Use `vLLMInvocationLayer` and a vLLM Server on another device (e.g. your local gpu server) to host your llama/mistral model there and consume it via `vLLMInvocationLayer`
- Use `vLLMLocalInvocationLayer` to run your models locally, on the same device you create the invocation layer.

**Comment by sumanghosh1234** [comment]
I have used vLLMInvocationLayer and a vLLM Server on another device  (GPU) . I can manually hit the /generate endpoint of the vLLM API server. But when I use it with Prompt Model / Node it fails


Stack Trace
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/nodes/prompt/prompt_model.py", line 111, in invoke
    output = self.model_invocation_layer.invoke(prompt=prompt, **kwargs)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/vllm_haystack/__init__.py", line 163, in invoke
    responses = self._execute_openai_request(
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/vllm_haystack/__init__.py", line 184, in _execute_openai_request
    _check_openai_finish_reason(result=res, payload=payload)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/utils/openai_utils.py", line 243, in _check_openai_finish_reason
    number_of_truncated_completions = sum(1 for ans in result["choices"] if ans["finish_reason"] == "length")
KeyError: 'choices'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/suman/virtualassitnt-mistral-rest-api/haystack-virtual-assistant-core/rest_api/controller/search.py", line 45, in query
    result = _process_request(query_pipeline, request)
  File "/home/suman/virtualassitnt-mistral-rest-api/haystack-virtual-assistant-core/rest_api/controller/search.py", line 53, in _process_request
    result = get_result(pipeline, query=request.query)
  File "/home/suman/virtualassitnt-mistral-rest-api/haystack-virtual-assistant-core/rest_api/pipelines/query.py", line 76, in get_result
    result = query_pipeline.run(query=query, params={"Retriever": {"top_k": 3}})
  File "/dev/anaconda3/envs/myenv/lib/python3.10/site-packages/haystack/pipelines/base.py", line 574, in run
    raise Exception(
Exception: Exception while running node 'PromptNode': 'choices'

**Comment by LLukas22** [comment]
I think you are hosting the wrong vLLM server, could you check that you host their "OpenAI compatible" server? It seams like your responses are missing the "choices" key which shouldn't be the case.

**Comment by sumanghosh1234** [comment]
I am running this  python -m vllm.entrypoints.openai.api_server --model mistralai/Mistral-7B-Instruct-v0.1
Because I want to use the mistral model.

**Comment by sumanghosh1234** [comment]
And when you say OpenAI compatible model what do you mean by that? Is it only GPT models?

**Comment by LLukas22** [comment]
With "openai compatible" i mean the API of your generation server,  `python -m vllm.entrypoints.openai.api_server` should create an openai compatible server meaning you should be able to consume it via the normal `openai` python package and by extension with this InvocationLayer. If your server is running check if you can infer it with the normal `openai` python package if that works, there probably were some changes in the API definition and i have to update the InvocationLayer.

**Comment by sumanghosh1234** [comment]
That will be really helpful @LLukas22  if we can make some changes which can support Mistral model as mentioned above. We are in Production and we are getting really slow response. This vLLM inference if we can make it work it will be great. Your help will be really appreciate if we can make Mistral instruct model work via vLLM - Haystack

**Comment by LLukas22** [comment]
Alright i tested the InvocationLayer against a vLLM server hosting `mistralai/Mistral-7B-Instruct-v0.1` and all the unit-test pass. Could you make sure that you vLLM server is actually openai compatible by trying to infer against it with the official openai package once? Also make sure to provide the URL correctly with the `/v1` at the end, other than that i would probably need more infos as i cant reproduce the error.

**Comment by sumanghosh1234** [comment]
Hi @LLukas22  I tried and it is working. Though I need your inputs on this. The answers that it is generating is not great. Is there a way if I want to use / generate endpoint of vllm. Will it be a big effort for you to add an adapter at vllm-haystack which can invoke  / generate endpoint of vllm can get the result?

**Comment by LLukas22** [comment]
I dont quite get, what you mean. The InvocationLayer currently hits the `v1/completions` endpoint as that is how the openai api is designed. I dont know what you mean with the `/generate` endpoint. It also shouldn't matter which endpoint you use as the underlying model will be the same, meaning it will produce the same results with the same request.

**Comment by sumanghosh1234** [comment]
If you check this https://github.com/vllm-project/vllm/blob/main/examples/api_client.py you can see that there is a /generate endpoint. Even if you look at the documentation https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html
they use /generate to generate the answers. Because when I am loading the mistral model locally as in using GGUF version by using llama-cpp layer then it is giving a very decent answer but it is taking a lot time because of the CPU machine. And then when I try the vLLM with Mistral via inferencing it is fast but answers not great.

**Comment by LLukas22** [comment]
It shouldn't matter which endpoint you use as the model gets the same prompt and sampling parameters either way. What you describ sounds like a sampling parameters problem where `llama.cpp` probably has good default values and the vLLM server has worse ones.
